FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
RUN wget https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine_1.19.0_amd64.deb
RUN dpkg -i hyperfine_1.19.0_amd64.deb
WORKDIR /src
COPY . .
RUN dotnet publish -f net8.0 /p:TargetFrameworks=net8.0
ENTRYPOINT ["hyperfine", "-r", "100", "./bin/Release/net8.0/publish/DotnetStartupPerformanceTest"]